.gitmodules, NaviGator/gnc/navigator_path_planner/package.xml, NaviGator/mission_control/navigator_launch/launch/simulation.launch, docker/base/system_install, docker/dev/Dockerfile, docker/dev/user_install, mil_common/utils/mil_tools/package.xml, scripts/build_docker_containers, scripts/run_development_container
=> Fix python imports

ci/readme.md, docs/culture.md, docs/development/adding_documentation.md, docs/development/contributing.md, docs/development/development_guide.md, docs/examples/index.rst, docs/onboarding.md, index.rst
* Update contributing guide to specify using upstream fork rather than user fork
* Add onboarding guide for basic getting started info 
* Various small fixes (broken links, etc)
=> Various documentation improvments

NaviGator/gnc/navigator_thrust_mapper/navigator_thrust_mapper/thruster_map.py, NaviGator/gnc/navigator_thrust_mapper/nodes/thrust_mapper.py
=> Update Navigator Thrust mapper for vrx

NaviGator/gnc/navigator_controller/nodes/mrac_controller.py, NaviGator/mission_control/navigator_launch/launch/gnc.launch, NaviGator/mission_control/navigator_launch/launch/gnc/controller.launch, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_controller.launch, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_localization.launch, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_master.launch
Seperate mrac gains into launch file
=> Tune controller for vrx

NaviGator/mission_control/navigator_launch/config/pcodar_vrx.yaml, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_controller.launch, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_tf.launch, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_upload_urdf.launch, NaviGator/simulation/navigator_gazebo/nodes/fix_hector_plugins, docs/onboarding.md
bla bla bla marshall knows what I mean, and he's the only one who will ever see this.
=> VRX: fix upstream frame issues causing localization instabilkity

docker/base/system_install
Also add some ML stuff (scipy, pandas)
=> INSTALL: use sudo for python pip installs

NaviGator/mission_control/navigator_launch/launch/vrx/vrx_controller.launch
=> Vrx gains 2

SubjuGator/scripts/bash_aliases.sh, docs/development/development_guide.md, docs/development/sub.md, docs/development/vrx.md, index.rst, scripts/setup.bash
Sub now has basic functionality in the mono repo on Ubuntu 18.04. Also there is a docs page with info about how to get started with sub.
=> Sub update

docker/dev/user_install, docs/development/index.rst, docs/development/using_the_dev_server.md, scripts/build_docker_containers, scripts/run_development_container, scripts/sshzobelisk
We can all use zobelisk now. See Proposed docs for demo
=> DEV: Dev server networked docker container

deprecated/sylphase-sonar/downsample, deprecated/sylphase-sonar/plot, deprecated/sylphase-sonar/plot_once, deprecated/sylphase-sonar/plot_pings, deprecated/sylphase-sonar/psd, deprecated/sylphase-sonar/ros_bridge, deprecated/sylphase-sonar/tcp_protocol.md, deprecated/sylphase-sonar/util.py, scripts/install_sylphase_sonar
Following a conversation with @forrestv, I am doing the following:
* Add a script to clone sylphase sonar package
* Migrate certain sylphase sonar files which Forrest approved to be open sourced into the repo for our reference and pottential use (for now these live in deprecated/ until we make use of them)
TODO
* Add to `system_install` the necessary dependencies (if any) to run sylphase sonar
=> INSTALL: script to install sylphase passive sonar

docs/mechanical/index.rst, docs/mechanical/onboarding.md, index.rst
=> DOCS: add docs page for mechanical team

.gitignore, docker/dev/user_install, docs/development/index.rst, docs/infra/network.md, scripts/rc.d/network_setup.sh, scripts/setup.bash
=> Ros connect redesign

.gitmodules, ci/lint_cpp
Might need some modifications to ignore when the flycapsdk isnt present
=> REPO: move pointgrey_camera_driver out of deprecated

docker/base/system_install, scripts/install_sylphase_sonar
=> Sylphase sonar install

SubjuGator/command/sub8_launch/launch/subsystems/passive_sonar.launch, SubjuGator/command/sub8_launch/scripts/passive_sonar_conn, SubjuGator/scripts/bagging_variables.sh, mil_common/drivers/mil_passive_sonar/scripts/run_sylphase_driver
=> LAUNCH: update sub8_launch for new passive sonar system

docs/culture.md, docs/mechanical/issuesM.md, docs/mechanical/mechanical.rst, docs/mechanical/onboarding.md, docs/mechanical/onboardingM.md, docs/mechanical/resourcesM.md, docs/testingprocedures.md, index.rst
Created some files for the mech documentation, created the testing procedure and updated the culture
Issue I had was that I was not able to find the mech dir that kev created before so the files are in /docs. Might have to move them later
=> Mech documentation and updates

SubjuGator/gnc/sub8_thruster_mapper/test/test_sub8_mapper.py
=> TESTS: increase timeout in sub8_thruster_mapper

docs/design/design.rst, docs/design/odom_estimator/odom_estimator.rst
See https://github.com/uf-mil/mil/issues/152#issuecomment-609362983.
=> DOCS: added design doc page for odom_estimator

docs/navigator/vrx.md
They have moved from Bitbucket to GitHub
=> Update VRX repository location

.gitignore, IndyAV/simulation/indyav_gazebo/CMakeLists.txt, IndyAV/simulation/indyav_gazebo/launch/spawn.launch, IndyAV/simulation/indyav_gazebo/launch/swan.launch, IndyAV/simulation/indyav_gazebo/scripts/generate_racetrack.py, IndyAV/simulation/indyav_gazebo/worlds/new_smyrna.world.xacro, IndyAV/simulation/indyav_gazebo/worlds/new_smyrna.xacro, IndyAV/simulation/indyav_gazebo/worlds/new_smyrna.yaml, docker/base/system_install
DEMO:
`roslaunch indyav_launch gazebo.launch`
`gazebogui`
view the racetrack and the car on that racetrack
=> INDYAV: Added race track generator

IndyAV/command/indyav_launch/launch/odometry.launch, IndyAV/command/indyav_launch/launch/tf.launch, IndyAV/command/indyav_launch/package.xml, IndyAV/localization/indyav_localization/CMakeLists.txt, IndyAV/localization/indyav_localization/package.xml, IndyAV/localization/indyav_localization/src/dumb_truth_tf.cpp, IndyAV/localization/indyav_localization/test/test_sylphase.py, IndyAV/localization/indyav_localization/test/test_sylphase.test, IndyAV/simulation/indyav_gazebo/urdf/indyav_car.urdf.xacro, docs/indyav/software/localization.rst, docs/indyav/software/simulation/gazebo/gazebo.dot
added sylphase and fixed_link_persistent xacros to xacro folder as they are required to add sylphase to indyav urdf. deleted p3d xacro instance and include, and added the same sylphase instance as from the navigator urdf
=> p3d to sylphase for indyav urdf

SubjuGator/command/sub8_launch/launch/can.launch
accidentally created a second branch for parse_andres_research. Merging new one with changes into original
=> port changes

SubjuGator/command/sub8_launch/launch/can.launch, SubjuGator/command/sub8_launch/launch/subsystems/cameras/launch/left_camera.launch, SubjuGator/command/sub8_missions/sub8_missions/pinger.py, SubjuGator/etc/netplan/01-netcfg.yaml.old, mil_common/gnc/odom_estimator/src/nodelet.cpp
Updated ports and netplan for new motherboard. Updating the ports for cameras are still required.
=> updated ports and netplan

SubjuGator/command/sub8_launch/launch/gazebo.launch, SubjuGator/command/sub8_launch/launch/sub8.launch, SubjuGator/command/sub8_launch/launch/subsystems/cameras.launch, SubjuGator/command/sub8_launch/launch/subsystems/cameras/launch/left_camera.launch, SubjuGator/command/sub8_launch/launch/tf.launch, SubjuGator/command/sub8_launch/launch/upload_urdf.launch, SubjuGator/simulation/sub8_gazebo/CMakeLists.txt, SubjuGator/simulation/sub8_gazebo/launch/duck.launch, SubjuGator/simulation/sub8_gazebo/launch/spawn.launch, SubjuGator/simulation/sub8_gazebo/urdf/sub8_no_cams.urdf.xacro
Created 'simulate_cams' parameter in gazebo.launch. Set it to true if you want to gazebo to simulate the cameras. Set it to false if you want to use the real front left camera data. You can test whether it works by checking the camera output through subviz.
=> Lucas cameras

NaviGator/scripts/bash_aliases.sh
nmove was aliased to runtask Move. It was updated to runmission Move.
=> Update nmove to use runmission

mil_common/drivers/mil_acoustic_modems/README.md, mil_common/drivers/mil_acoustic_modems/sendercommLaptop.py, mil_common/drivers/mil_acoustic_modems/serialListenLaptop.py
Adding the base scripts for the acoustic modem testbed
=> added acoustic modem base scripts and directory

scripts/setup.bash
vrx="$MIL_REPO/NaviGator/simulation/VRX/vrx"
=> added vrx alias

docs/development/contributing.md, docs/development/development_guide.md, docs/development/getting_started.md, docs/development/index.rst, docs/navigator/vrx.md
You can check the new documentation by executing from the root of the repository:
```./scripts/build_docs```
```./scripts/display_docs```
=> updating the onboarding guide

docs/mechanical/drone_docM.md, docs/mechanical/maintenanceM.md, docs/mechanical/mechanical.rst, docs/mechanical/onboardingM.md, docs/mechanical/resourcesM.md
Documentation of after the meeting with the Aerotetra founder about the drone and documentation about CNC maintenance
=> Mech and Drone documentation

docs/development/apple_mseries_ubuntu_setup.md, docs/development/getting_started.md, docs/development/index.rst
This pull request includes information about installing Ubuntu on Darwin/Apple computers with an M-series processor.
Closes #365.
=> Update Ubuntu installation documentation for M-series Apple computers

NaviGator/mission_control/navigator_launch/launch/vrx/vrx_beacon.launch, NaviGator/mission_control/navigator_launch/launch/vrx/vrx_master.launch, NaviGator/simulation/navigator_gazebo/CMakeLists.txt, NaviGator/simulation/navigator_gazebo/nodes/acoustic_beacon.py, NaviGator/utils/navigator_msgs/CMakeLists.txt, NaviGator/utils/navigator_msgs/srv/AcousticBeacon.srv
Wrote a service that you can call which calculates the position of the acoustic beacon from the odom data and the range, bearing, and elevation data from the simulated hydrophone. When you call this service, if data from either service hasn't been received then setValue will be false to indicate the position value in the message is wrong.
Closes #369
=> VRX Beacon finding service

NaviGator/utils/remote_control/navigator_keyboard_control/nodes/navigator_keyboard_client.py, NaviGator/utils/remote_control/navigator_keyboard_control/nodes/navigator_keyboard_server.py, NaviGator/utils/remote_control/navigator_keyboard_control/remote_control_lib/remote_control_lib.py
#434 fixed, updated packages to python3.
=> Fix Issue #434

NaviGator/mission_control/navigator_launch/launch/vrx/vrx_tf.launch
Corrected vrx_tf.launch so that we don't get more tf issues.
=> corrected vrx tf launch file for imu and gps

NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wildlife.py, NaviGator/simulation/navigator_gazebo/nodes/circle_animal.py, NaviGator/vrx.rviz
Made it to where boat goes through midpoint between start and end position to make sure boat takes somewhat straight path from A->B. Made it to where the starting point of the circle the boat traces around the animal is on the line between the start boat position and the updated animal position. I also fixed a bug in how the "is the croc in the rectangle" math works.
=> Adjusted wildlife task to pass new worlds

.github/workflows/rtd.yml, conf.py, docker/noetic/Dockerfile, requirements-rtd.txt
Includes the new build pattern for the noetic docs build.
=> New noetic docs build

.github/workflows/rtd.yml, NaviGator/utils/navigator_msgs/srv/ChooseAnimal.srv, docs/reference.rst
Add documention of several messages, services, and actions in the `navigator_msgs` package.
=> Add documention of `navigator_msgs`, convert to py3

NaviGator/gnc/navigator_controller/nodes/mrac_controller.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx.py, NaviGator/simulation/navigator_gazebo/nodes/long_trajectory.py
Still need to test all stationkeeping, wayfinding, and wildlife worlds to see if long trajectory still functions properly.
=> Made threshold for long trajectory goal smaller (for wayfinding task)

NaviGator/simulation/navigator_gazebo/worlds/scan_dock_deliver_ambient.world, NaviGator/simulation/navigator_gazebo/worlds/scan_dock_deliver_foggy_ambient.world
Added a new scan-dock-deliver world, scan_dock_deliver_ambient.world, that changes ambient lighting and the color sequence of the stc buoy for future testing of the stc color thresholds.
=> Added new ambient lighting world for testing

docs/_static/custom.js, docs/_templates/layout.html
This adds increased support for mobile devices in the Alabaster docs.
=> Added hamburger menu on mobile, fix sidebar expanding in Alabaster docs

docs/development/index.rst, docs/development/resetubuntupass.md
Created documentation for Resetting Ubuntu Password
=> Add instructions to reset Ubuntu password

ci/build_docs, docs/_static/custom.css, docs/_static/custom.js, docs/extensions/attributetable.py, docs/reference.rst
Adds support for creating tables containing a list of functions and attributes for a C++ class.
=> Add attribute tables for C++ in noetic docs

mil_common/utils/mil_poi/mil_poi/__init__.py, mil_common/utils/mil_poi/mil_poi/server.py, mil_common/utils/mil_poi/mil_poi/tx_interface.py
migrate package mil/mil_common/utils/mil_poi/mil_poi
used the porting guide on MIL docs and used commands found there to check.
=> Migrate `mil_common/utils/mil_poi/mil_poi` package from python 2 to 3

SubjuGator/command/sub8_launch/scripts/tf_republisher.py
This migrates this package to Python 3 for support with ROS Noetic.
=> Migrate `sub8_launch` package to py3

SubjuGator/drivers/sub8_actuator_board/package.xml, SubjuGator/drivers/sub8_actuator_board/setup.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/__init__.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/handle.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/packets.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/simulation.py, conf.py, docs/sub_reference.rst, index.rst
This PR migrates this package, adding documentation and ensuring the package's compatibility with Python 3.
=> Migration of `sub8_actuator_board` package

conf.py
=> Fix broken Python Requests intersphinx link

docs/subjugator/reference.rst
=> Migrate the `sub8_pointcloud` package to ROS Noetic and Python 3, add documentation

SubjuGator/simulation/sub8_gazebo/diagnostics/__init__.py, SubjuGator/simulation/sub8_gazebo/diagnostics/gazebo_tests/__init__.py, SubjuGator/simulation/sub8_gazebo/diagnostics/gazebo_tests/align_marker_test.py, SubjuGator/simulation/sub8_gazebo/diagnostics/gazebo_tests/common.py, SubjuGator/simulation/sub8_gazebo/diagnostics/gazebo_tests/test_buoy_bump.py, SubjuGator/simulation/sub8_gazebo/diagnostics/gazebo_tests/test_simple_motion.py, SubjuGator/simulation/sub8_gazebo/diagnostics/job_runner.py, SubjuGator/simulation/sub8_gazebo/diagnostics/set_model_position_test.py, SubjuGator/simulation/sub8_gazebo/nodes/actuator_sim.py, SubjuGator/simulation/sub8_gazebo/nodes/buoys.py, SubjuGator/simulation/sub8_gazebo/nodes/fake_perception.py, SubjuGator/simulation/sub8_gazebo/nodes/gazebo_controller.py, SubjuGator/simulation/sub8_gazebo/nodes/pinger_tf_pub.py, SubjuGator/simulation/sub8_gazebo/nodes/turbulator.py, SubjuGator/simulation/sub8_gazebo/setup.py, SubjuGator/simulation/sub8_gazebo/sub8_gazebo_tools/__init__.py, SubjuGator/simulation/sub8_gazebo/sub8_gazebo_tools/bag_manager.py, docs/subjugator/reference.rst
=> Migrate `sub8_gazebo` package from Python 2 to Python 3, document needed classes

docs/development/python_style.md
This PR updates the Python style guide with two minor changes. The related issues which this PR fixed can be found here:
- #448 
- #593
Thanks!
=> Update Python style guide with new formatting and guidelines

docs/development/getting_started.md, docs/development/noetic_migration.md
This PR updates the Noetic Migration docs. This PR closes two issues:
- #435
- #446
=> Update Noetic Migration docs, add warning about installing Ubuntu 18 for Noetic

docs/reference.rst, mil_common/drivers/sabertooth2x12/nodes/sabertooth2x12ros, mil_common/drivers/sabertooth2x12/sabertooth2x12/__init__.py, mil_common/drivers/sabertooth2x12/sabertooth2x12/board.py, mil_common/drivers/sabertooth2x12/sabertooth2x12/simulated.py, mil_common/drivers/sabertooth2x12/setup.py
=> Migrate the `sabertooth2x12` package to Noetic, Python 3, add documentation

mil_common/gnc/rawgps_common/src/rawgps_common/bitstream.py, mil_common/gnc/rawgps_common/src/rawgps_common/glonass.py, mil_common/gnc/rawgps_common/src/rawgps_common/gps.py
=> Migrate `rawgps_common` to Python 3 and ROS Noetic

docs/reference.rst, mil_common/mil_missions/mil_missions_core/__init__.py, mil_common/mil_missions/mil_missions_core/base_mission.py, mil_common/mil_missions/mil_missions_core/chain_with_timeout.py, mil_common/mil_missions/mil_missions_core/exceptions.py, mil_common/mil_missions/mil_missions_core/mission_client.py, mil_common/mil_missions/mil_missions_core/mission_result.py, mil_common/mil_missions/mil_missions_core/wait.py, mil_common/mil_missions/mil_missions_examples/__init__.py, mil_common/mil_missions/mil_missions_examples/base_mission.py, mil_common/mil_missions/mil_missions_examples/print_and_wait.py, mil_common/mil_missions/mil_missions_examples/publish_things.py, mil_common/mil_missions/mil_missions_examples/super_mission.py, mil_common/mil_missions/mil_missions_gui/__init__.py, mil_common/mil_missions/mil_missions_gui/dashboard.py, mil_common/mil_missions/nodes/mission_client, mil_common/mil_missions/nodes/mission_server, mil_common/mil_missions/setup.py
=> Migrate `mil_missions` to ROS Noetic, Python 3

SubjuGator/simulation/sub8_simulation/nodes/dynamics_simulator, SubjuGator/simulation/sub8_simulation/nodes/simulate.py, SubjuGator/simulation/sub8_simulation/nodes/spacenav_remap.py, SubjuGator/simulation/sub8_simulation/setup.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/__init__.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/meshes/__init__.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/meshes/meshes.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/physics/__init__.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/physics/physics.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/physics/vehicle.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/rendering/__init__.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/rendering/visualization.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/rendering/world.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/shaders/__init__.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/shaders/shader_manager.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/shaders/shaders.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/widgets/__init__.py, SubjuGator/simulation/sub8_simulation/sub8_sim_tools/widgets/sub.py
- #628
This PR does not add documentation.
=> Migrate the `sub8_simulation` package to Python 3 for ROS Noetic support

NaviGator/utils/voltage_gui/setup.py, NaviGator/utils/voltage_gui/src/voltage_gui.py
=> Update the `voltage_gui` package to Python 3 for ROS Noetic support

SubjuGator/gnc/sub8_system_id/setup.py, SubjuGator/gnc/sub8_system_id/sub8_system_id/__init__.py, SubjuGator/gnc/sub8_system_id/sub8_system_id/dynamics.py, docs/subjugator/reference.rst
=> Migrate the `sub8_system_id` package to Python 3 and add Alabaster documentation

SubjuGator/gnc/sub8_controller/nodes/adaptive_controller
This PR closes the following:
- #717
=> Migrate the `sub8_controller` package to Python 3

NaviGator/perception/navigator_vision/navigator_vision/__init__.py, NaviGator/perception/navigator_vision/navigator_vision/scan_the_code_classifier.py, NaviGator/perception/navigator_vision/navigator_vision/vrx_color_classifier.py, NaviGator/perception/navigator_vision/navigator_vision/vrx_stc_color_classifier.py, NaviGator/perception/navigator_vision/nodes/bbox_pcodar, NaviGator/perception/navigator_vision/nodes/database_color.py, NaviGator/perception/navigator_vision/nodes/detect_deliver_target, NaviGator/perception/navigator_vision/nodes/object_classifier.py, NaviGator/perception/navigator_vision/nodes/scan_the_code.py, NaviGator/perception/navigator_vision/nodes/shooter_finder.py, NaviGator/perception/navigator_vision/nodes/start_gate_manual.py, NaviGator/perception/navigator_vision/nodes/vrx_classifier.py, NaviGator/perception/navigator_vision/setup.py, mil_common/perception/mil_vision/mil_vision_tools/objects_tracker.py, mil_common/utils/mil_tools/mil_ros_tools/image_helpers.py
=> Migrate the `navigator_vision` package to Python 3 and format

NaviGator/simulation/navigator_gazebo/nodes/acoustic_beacon.py, NaviGator/simulation/navigator_gazebo/nodes/circle_animal.py, NaviGator/simulation/navigator_gazebo/nodes/fix_hector_plugins, NaviGator/simulation/navigator_gazebo/nodes/gazebo_controller.py, NaviGator/simulation/navigator_gazebo/nodes/long_trajectory.py, NaviGator/simulation/navigator_gazebo/nodes/sim_hydrophones.py, NaviGator/simulation/navigator_gazebo/nodes/two_closest_cones.py, NaviGator/simulation/navigator_gazebo/test/test_sim_integration.py
=> Migrate the `navigator_gazebo` package to Python 3

NaviGator/test/navigator_test/navigator_test_lib/__init__.py, NaviGator/test/navigator_test/navigator_test_lib/spoof.py, NaviGator/test/navigator_test/navigator_test_lib/test_unit.py, NaviGator/test/navigator_test/navigator_testing_suite/__init__.py, NaviGator/test/navigator_test/navigator_testing_suite/mission_perception_test/__init__.py, NaviGator/test/navigator_test/navigator_testing_suite/mission_perception_test/find_the_break_test_perception.py, NaviGator/test/navigator_test/navigator_tests/__init__.py, NaviGator/test/navigator_test/navigator_tests/mission_planner_no_markers_test.py, NaviGator/test/navigator_test/navigator_tests/mission_planner_test.py, NaviGator/test/navigator_test/navigator_tests/odom_spoofer.py, NaviGator/test/navigator_test/nodes/circle_sim.py, NaviGator/test/navigator_test/nodes/test_tool.py, NaviGator/test/navigator_test/setup.py
=> Migrate the `navigator_test` package to Python 3, add support for ROS Noetic

mil_common/gnc/mil_bounds/cfg/BoundsConfig.cfg, mil_common/gnc/mil_bounds/mil_bounds/__init__.py, mil_common/gnc/mil_bounds/mil_bounds/bounds.py, mil_common/gnc/mil_bounds/nodes/bounds_from_rviz, mil_common/gnc/mil_bounds/nodes/bounds_server, mil_common/gnc/mil_bounds/setup.py, mil_common/gnc/mil_bounds/test/test_bounds.py
https://github.com/uf-mil/mil/issues/532
=> Noetic mil bounds

NaviGator/utils/navigator_robotx_comms/navigator_robotx_comms/navigator_robotx_comms.py, NaviGator/utils/navigator_robotx_comms/nodes/robotx_comms_client.py
Unit test case results shown below.
Attached is also the unit test script. Not sure if it would be good to add to the repo.
[UnitTest.zip](https://github.com/uf-mil/mil/files/9176636/UnitTest.zip)
=> Update `system_mode` in `navigator_robotx_comms` package to use `IntEnum`

docs/subjugator/index.rst, docs/subjugator/lessons19.md, docs/subjugator/lessons22.md, docs/subjugator/robosub.md
This PR aims to add more docs related to the RoboSub competition (and the 2019 competition), alongside improving the docs for what we learned in the 2022 competition.
=> Added robosub general page, robosub19 lessons and extended robosub22 lessons

NaviGator/mission_control/navigator_launch/launch/vrx/vrx_classifier.launch, NaviGator/mission_control/navigator_missions/vrx_missions/gymkhana.py, NaviGator/mission_control/navigator_missions/vrx_missions/scan_the_code.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_station_keeping.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_station_keeping_2.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wayfinding.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wayfinding_2.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wildlife.py, NaviGator/perception/navigator_vision/nodes/vrx_classifier.py, README.md, SubjuGator/command/sub8_missions/sub8_missions/sub_singleton.py
Fixed vrx missions. Scan Dock Deliver still won't work because I didn't train the current yolo model to detect some of the things needed for this task to work. Tasks 1-4 were tested and work fine, task 5 will be tested later on a computer with a gpu, but it is assumed to work fine currently because tasks 1-4 work.
=> Vrx vision yolov7

docs/navigator/vrx.rst
=> Change link to RST format

NaviGator/mission_control/navigator_missions/vrx_missions/gymkhana.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_station_keeping.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_station_keeping_2.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wayfinding.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wayfinding_2.py, NaviGator/mission_control/navigator_missions/vrx_missions/vrx_wildlife.py, NaviGator/perception/navigator_vision/nodes/vrx_classifier.py, NaviGator/simulation/navigator_gazebo/CMakeLists.txt
Disabled locking mechanism at the start of missions and simplified pcodar reset at beginning of sim. In order to test, you will need to full compile (rm devel and build) at least once.
=> Issue 602 - Disabled Locking of Boat in VRX

NaviGator/utils/navigator_robotx_comms/navigator_robotx_comms/navigator_robotx_comms.py, docs/navigator/reference.rst
Added documentation for Heartbeat messages and classes.
=> Added documentation for new heartbeat messages and classes

.github/workflows/issue_comment_non_member.yaml
=> Updated issue_comment_non_member

docs/testingprocedures.md
This PR serves to update the packing list for testing events for RobotX 2022.
=> Update packing list for NaviGator/RobotX 2022

.github/ISSUE_TEMPLATE/navigator.yaml, .github/PULL_REQUEST_TEMPLATE.md
This PR adds a template for making new GitHub pull requests and issues.
=> Add pull request template and software issue template

.github/ISSUE_TEMPLATE/navigator.yaml, .github/PULL_REQUEST_TEMPLATE.md
This PR fixes the validation issues with the GitHub templates added in #865.
No screenshot is relevant to this PR.
* None
View the file in GitHub web and notice that the issue form is successfully generated without any validation errors.
=> Fix GitHub templates

scripts/install.sh
Add 256 color support as part of the install script
* Closed #829
=> [tmux] Add 256 color support as part of the install script

docs/software/calibrating_cams.md, docs/software/index.rst
This PR adds documentation on how to calibrate a new camera.
Not useful
* None
None, view docs preview.
=> Add docs on camera calibration

NaviGator/mission_control/navigator_launch/launch/simulation.launch
Added new Yolo model. If you have an Nvidia gpu, you would be able to test the vision system.
=> Added new yolo model

docs/software/index.rst, docs/software/rostest.md
This PR adds docs on:
* Using `rostest` and writing `.test` files
* Using `unittest` to write Python tests cases
See docs output.
* #902
None, see docs output.
=> Add docs on using `unittest` and `rostest`

mil_common/mil_missions/nodes/mission_client, mil_common/mil_missions/nodes/mission_server
This PR fixes the following:
* Publishers publishing to the same topic do not work if publishing to a previously published topic
* `mission refresh` would get stuck on an action server
None
* None
View that CI tests pass.
=> Fix mission refresh command and publisher re-connection issue

docs/navigator/index.rst, docs/navigator/networking.dot, docs/navigator/networking.md
This PR adds basic docs on using the Ubiquiti networking setup on NaviGator.
None, just docs.
* None
None, see docs build.
=> Add docs on using Ubiquiti

scripts/cli/mission.py
I added the mission refresh command to the mil command line interface. Now, whenever anyone types in "mil mission refresh", it runs the same exact thing as mission refresh.
* #XXX
=> Add `mil mission refresh` to `mil` CLI

scripts/install.sh
This PR adds a command to the MIL setup script to disable the Ubuntu new version available prompt.
Not relevant
* #XXX
* Run the setup script and observe no issues occurring
=> Disable the "Auto Updates" Ubuntu prompt

SubjuGator/command/sub8_launch/launch/mission_server.launch, SubjuGator/command/sub8_missions/sub8_missions/sub_singleton.py
Fixes:
* `mission refresh` works with SubjuGator missions
* Adds proper `shutdown()` functionality to main SubjuGator mission class
Run the simulation and run a mission. Then, change the mission, run `mission refresh`, and observe that the mission behavior has changed!
=> Fix two issues with SubjuGator missions

docs/reference/messages.rst
Fixed documentation error
Closed #944
* #XXX
=> Fixed bug #944

mil_common/drivers/mil_usb_to_can/mil_usb_to_can/simulation.py
Fixes a mutable argument in SimulatedUSBtoCAN.
* Closed #663
=> Fixed bug #663

scripts/cli/mission.py
… 
The CLI script can now launch the mission_client node and execute the list command. Thus, the command 'mil mission list' should now be able to list all the available missions that can be ran.
* #914
=> Implemented mil mission list in the mil CLI

NaviGator/utils/remote_control/navigator_emergency_control/nodes/navigator_emergency.py
I added docstrings to several functions within the file and defined the appropriate types for each object. 
* #XXX
Run several test cases or the debug tool to pinpoint the error.
=> DocString and Types Edit to "navigator_emergency_control" file

scripts/install.sh, scripts/setup.bash
This PR adds some common `apt` packages to our install scripts to make setup easier.
None, few lines change.
Closes #1022 
Re-run the install script.
=> Add helpful Linux tools to install script

SubjuGator/command/subjugator_launch/launch/can.launch, SubjuGator/command/subjugator_missions/subjugator_missions/sub_singleton.py, SubjuGator/drivers/sub8_actuator_board/CMakeLists.txt, SubjuGator/drivers/sub8_actuator_board/package.xml, SubjuGator/drivers/sub8_actuator_board/setup.py, SubjuGator/drivers/sub8_actuator_board/srv/SetValve.srv, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/__init__.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/handle.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/packets.py, SubjuGator/drivers/sub8_actuator_board/sub8_actuator_board/simulation.py, mil_common/drivers/mil_usb_to_can/mil_usb_to_can/sub8/__init__.py
=> Fix mil_usb_to_can driver by updating sub_actuator_board

docs/software/getting_started.md
Fixes the iso links in the docs
=> Fix iso links in getting started docs

NaviGator/mission_control/navigator_launch/launch/vrx/vrx_tf.launch
Adds a parameter to the VRX TF launch file to silence unnecessary warnings.
\- Closes #XXX
=> Add param to reduce TF warnings in VRX

scripts/setup.bash
Forgot to make this change after #1138 oopsies
\- Closes #XXX
=> Add `DCATKIN_WHITELIST_PACKAGES=""` to `cm`

NaviGator/utils/navigator_msgs/CMakeLists.txt, NaviGator/utils/navigator_msgs/action/ShooterDo.action, NaviGator/utils/navigator_msgs/msg/DockShape.msg, NaviGator/utils/navigator_msgs/msg/PoseTwistStamped.msg, NaviGator/utils/navigator_msgs/package.xml, NaviGator/utils/navigator_msgs/srv/CameraToLidarTransform.srv
=> Convert navigator_msgs to ROS2

scripts/install.sh, scripts/setup.bash
=> Add shell alias for viewing CPU temp

docs/navigator/reference.rst, docs/subjugator/reference.rst
This is a big one
\- Closes #XXX
=> The single biggest, most important change I have made in MIL

mil_common/mil_missions/CMakeLists.txt, mil_common/mil_missions/include/client.h, mil_common/mil_missions/include/mil_missions/client.h, mil_common/mil_missions/package.xml, mil_common/mil_missions/src/client.cpp, mil_common/mil_missions/test/run_mission_cpp.test, mil_common/mil_missions/test/run_mission_py.test, mil_common/mil_missions/test/test_run_mission.cpp, mil_common/mil_missions/test/test_run_mission.py
This PR adds a C++ interface for `mil_missions`, which can be used for efficiently testing missions in C++.
\- Closes #XXX
=> Add C++ library for `mil_missions`

SubjuGator/command/subjugator_launch/launch/subsystems/odometry.launch, mil_common/gnc/odom_estimator/src/nodelet.cpp
=> odom_estimator: small ECEF coordinate updates

mil_common/mil_missions/CMakeLists.txt
(related to #1204)
\- Closes #XXX
=> Fix `mil_missions` missing library dependency

.github/ISSUE_TEMPLATE/software.yaml
=> issue template: Remove unnecessary fields at bottom of issue (closes #1132)

mil_common/ros_alarms/nodes/monitor
=> ros_alarms/nodes/monitor: Break when rosmaster shuts down

SubjuGator/command/subjugator_alarm/CMakeLists.txt, SubjuGator/command/subjugator_alarm/alarm_handlers/__init__.py, SubjuGator/command/subjugator_alarm/alarm_handlers/temp.py, SubjuGator/command/subjugator_alarm/launch/alarms.launch, SubjuGator/command/subjugator_alarm/test/temp.test, SubjuGator/command/subjugator_alarm/test/temp_test.py, requirements.txt
=> ros_alarms: Add high CPU temperature alarm

NaviGator/mission_control/navigator_launch/launch/vrx/vrx_controller.launch
Updated the PID controller for the simulation and wave parameters to reduce the amount of rocking the boat experiences.
There is still some rocking but it is a minimal amount.
Closes  #1287
`roslaunch navigator_launch simulation.launch`
`amonitor kill` and unkill the boat
`nmove rviz 0`
`nviz` and select a 2D navigation pose and view that it is much smoother.
=> Fixes rocking issue

.github/workflows/ci.yaml, .github/workflows/pre-commit.yaml, .pre-commit-config.yaml, requirements.txt
=> .github: Move pre-commit checks to local self-hosted runners

docs/navigator/testing_checklist.rst
update NaviGator mechanical testing checklist
simple adding more items
NA
\- Closes #XXX
build docs
=> update NaviGator mechanical testing checklist

NaviGator/mission_control/navigator_launch/config/bounds_sarasota_a.yaml, NaviGator/mission_control/navigator_launch/config/bounds_sarasota_b.yaml, NaviGator/mission_control/navigator_launch/config/bounds_sarasota_c.yaml
Added ecf coordinate bounds for RobotX 2024 in Sarasota.
=> added ecf bounds for sarasota 2024
