uf-mil/mil

- .gitignore
- NaviGator/mission_control/navigator_launch/launch/vrx.launch
- NaviGator/mission_control/navigator_launch/package.xml
- NaviGator/simulation/navigator_gazebo/CMakeLists.txt
- NaviGator/simulation/navigator_gazebo/urdf/navigator_vrx/sensor_config.yaml
- NaviGator/simulation/navigator_gazebo/urdf/navigator_vrx/thruster_config.yaml
- scripts/build_docker_containers
- scripts/run_development_container
- scripts/run_vrx_container
current status, please advise:
Added vrx.launch(currently does not launch navigator_vrx.urdf). Added navigator_vrx.urdf generation at compile time (currently runs every time, not sure why will not run without ALL). Added a generate_navigator_vrx bash script(this must be done so that the command is run wit hwrtie permissions). Added sensor_config.yaml and thruster_config.yaml for vrx wamv gerneation. Accidentally edited and fixed conf.py(should be identical to master). Changed dev/Dockerfile to have UID=1000 (it was 10000). VRX containers are now built when build_containers is run(currently intel only, no nvidia containers(this will be nessesary to use GPU acceleration in VRX containers later)). Development container now uses an anonymous volume, not a bind mount. Added a script to run the …
> Vrx urdf generation

- mil_common/perception/point_cloud_object_detection_and_recognition/src/object.cpp
Lagforded ya kev
PCODAR: longer accumulates all points in an object. Becomes way to slow to be practical. Missions will have to accumulate their own points as needed from here on out.
> PCODAR: made pcodar fast again

- scripts/build_docker_containers
- scripts/run_development_container
The Dev container build and devel directories are now saved under the ~/.mil/dev-docker-ws directory. This way we do not have to recompile every time we login to the dev container.
DEMO:
`./scripts/build_docker_containers`
`./scripts/run_development_container`
`cm`
`exit`
`./scripts/run_development_container`
`tmux`
`roslaunch sub8_launch gazebo.launch gui:=true`
*new panel*
`amonitor kill`
`Shift+c`
*new panel*
`submove f 1`
witness the sub move
> DEV: Dev Container now saves build and devel on host machine

- ci/lint_cpp
Fixes the annoying
```
Is a directory
````
messages in CI lint stage
> CI: correctly ignore directories in lint_cpp

- docker/dev/Dockerfile
Correctly builds the dev image from the correct base image in the CI process by using the MIL_DOCKER_BASE_IMAGE env variable
> CI: build dev image off env variable base

- docker/base/system_install
- mil_common/gnc/mil_bounds/CMakeLists.txt
Not sure how / why this was like this or why it stopped working, but it definitely doesn't compile anymore. It now is the same a sother test CMakeLists's and the bounds test still executes successuflly.
> Fixed mil_bounds test

- docs/development/development_guide.md
- index.rst
Many new people trying to get through the dev guide have contacted me confused about running the bash scripts in the dev guide, so I added a section on how to get to the root of the repo and why.
> DOCS: Dev guide added root-repo instructions

- docs/development/development_guide.md
- scripts/build_docker_containers
previously, when building the docker containers for the first time, the container launches, but does not compile and is not interactive. This PR fixes that.
> DOCKER: fixed run dev container at the end of the docker build script

- IndyAV/command/indyav_launch/launch/controls.launch
- IndyAV/command/indyav_launch/launch/joydrive.launch
- IndyAV/command/indyav_launch/package.xml
- IndyAV/control/indyav_control/CMakeLists.txt
- IndyAV/control/indyav_control/src/joy_teleop.cpp
- IndyAV/control/indyav_control/src/simulated_steering_driver.cpp
- docs/indyav/software/control/control.rst
- docs/indyav/software/control/joydrive/joydrive.rst
- docs/indyav/software/software.rst
**Setting up an Xbox 360 controller**
Plug in the controller and check to see if it is recognized.
`ls /dev/input/`
This outputs a list of input devices in the format shown below:
```
by-id    event0  event2  event4  event6  event8  mouse0  mouse2  uinput
by-path  event1  event3  event5  event7  js0     mice    mouse1
```
Joysticks will be listed as jsX.
**Running the utility**
Launch the Joydrive.
`roslaunch indyav_launch joydrive.launch`
By default, js0 is used by the joydrive utility. To use a different input device, pass the name of the input device using the "js" argument.
`roslaunch indyav_launch joydrive.launch js:=js1`
In a new panel, launch Gazebo for IndyAV.
`roslaunch indyav_launch gazebo.launch`
In a new panel, launch RVIZ for IndyAV.
`indyviz`
In a new panel, launch the …
> INDYAV: revised implementation for joydrive utility

- NaviGator/mission_control/navigator_launch/launch/vrx/vrx_localization.launch
fixed the deprecated variable broadcast_utm_transform to broadcast_cartesian_transform under Navigator/mission_control/navigator_launch/launch/vrx/vrx_localization.launch
tested runmission Move f 5, looks like it works
Also, another instance of the deprecated variable exists within the VRX directory, but changing it seemed to have strange effects to Git so it was left alone.
> Fixed NavSat Deprecated Variable

- NaviGator/scripts/bash_aliases.sh
- SubjuGator/scripts/bash_aliases.sh
- docker/base/system_install
- docker/dev/user_install
- scripts/setup.bash
The setup scripts (`.../scripts/system_install` and `.../scripts/user_install`) have been updated with the following features:
- Support for `zsh` and `.zsh` ROS files
- Support for installing `ros-noetic` apt packages
- Support for installing Python 3 dependencies
Closes #396, closes #397.
> Update setup scripts for ROS Noetic

- NaviGator/gnc/navigator_msg_multiplexer/nodes/ogrid_arbiter.py
The first package to be migrated as part of the ROS Noetic migration!
Includes more typing support and function docstrings. Most of the core code was unchanged.
Closes #389.
> Migrate `navigator_msg_multiplexer` package from Python 2 to Python 3

- docs/development/index.rst
- docs/development/submodule.md
Our documentation lacks reliable methods for working with submodules in our repository. I added a brief list of commands that can be used to get/make changes to submodules in our repository.
Closes #401.
> Add documentation on working with submodules

- scripts/kill_process.sh
- scripts/kill_ros.sh
- scripts/setup.bash
This fixes the issue of straggling process and nodes being left over after an ungraceful stop to ROS. By deleting every process with "rosmaster" or "gazebo", the engineer can just run the "killros" alias to clean up.
This can be tested by running 
`roslaunch navigator_launch vrx.launch run_task:=True world:=stationkeeping_task --screen`
and using `ctrl + \` to simulate an ungraceful stop.
Use `ps aux | grep -f 'gazebo` and `ps aux | grep -f 'rosmaster` to see unkilled processes.
Now, use the alias `killros` to select which processes you want to delete, if not all of them.
try launching ros after this, it will run correctly.
> Created bash files kill_ros.sh and kill_process.sh for cleanup

- docker/base/system_install
Closes #436.
This PR modifies/adds some commands to the ROS Noetic setup scripts. It adds:
* Installation of `black` and `modernize` through `pip3`
* Installation of `tensorflow==2.8.0` rather than `tensorflow==2.1.0` through `pip3`
* A fallback to install `vcstool` from `pip3` rather than `apt` if the `apt` command fails
This PR does **not** fix a potential issue occurring with an improper `numpy` dependency when installing `pandas`. Currently, there is not enough information to fix this, so for now, I believe it's best to handle this on a case by case basis.
> Add commands to target ROS Noetic setup scripts issues

- docs/development/getting_started.md
- scripts/store_git.sh
Adds a script to setup a credential manager for Git. This script helps new (and old) members:
* Setup their name and email with `git config`
* Download and install the GitHub CLI, `gh`
* Authenticate `git` with `gh auth login` so that pushing to the repo is possible
> Add Git credential manager

- SubjuGator/simulation/sub8_gazebo/worlds/a_whole_new.world
- mil_common/gnc/odom_estimator/src/nodelet.cpp
- mil_common/utils/mil_tools/mil_ros_tools/vector_to_marker
You can launch ```roslaunch sub8_launch gazebo.launch``` and see no red errors.
> Fixed odom estimator to not die at launch and enabled pinger to exist by default

- docker/base/system_install
Currently, the Noetic script doesn't install `python3` and `python3-pip` before attempting to install `vcstool` with `pip3`. This breaks the script. This PR adds a fix to prevent this break from happening.
> Fix python3 issue with script

- NaviGator/simulation/navigator_gazebo/worlds/wayfinding_largewave.world
- NaviGator/simulation/navigator_gazebo/worlds/wayfinding_largewave_alt.world
- NaviGator/simulation/navigator_gazebo/worlds/wayfinding_largewavewind.world
- NaviGator/simulation/navigator_gazebo/worlds/wayfinding_largewavewind_alt.world
- NaviGator/simulation/navigator_gazebo/worlds/wayfinding_largewind.world
- NaviGator/simulation/navigator_gazebo/worlds/wayfinding_largewind_alt.world
**Commit 1**
Added new wayfinding task worlds that are harder:
-wayfinding_largewave.world (only the wave parameters and waypoints are changed)
-wayfinding_largewind.world (only the wind parameters and waypoints are changed)
-wayfinding_largewavewind.world (the wind, wave, and waypoints are changed)
Each of the new worlds have new waypoint locations, different from the other new world files. The direction of the waves and wind are also changed in some new world files as well. 
**Commit 2**
Added three new wayfinding worlds with names "alt". These worlds match up better with the parameters specified in vrx2022 technical guide. I kept the other worlds as well in case we want to use them for additional testing. Some parameters do not fall within the ones vrx will give, but the values are …
> Added new wayfinding world files

- NaviGator/utils/navigator_battery_monitor/nodes/navigator_battery_monitor.py
- conf.py
- docs/reference.rst
This adds documentation and py3 capability for the Navigator battery monitor.
> Convert battery monitor to py3 and document

- docs/extensions/attributetable.py
In the previous PR (#556), some lines were accidentally included that caused building on new computers to break (including the inclusion of the `rich` library).
> Add fixes to C++ docs building

- ci/build_docs
The build is currently failing because of the Doxygen build process being commented out.
> Removing commenting of Doxygen to allow for full building

- .github/workflows/rtd.yml
- ci/build_docs
- docker/base/system_install
added a flag -D to the script "./scripts/build_docs" to enable rebuilding the C++ docs with Doxygen
running "./scripts/build_docs" without -D rebuilds the C++ docs without Doxygen
> flag -D added to build_docs script to build docs with Doxygen enabled

- conf.py
- docs/reference.rst
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/__init__.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/application_packet.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/board.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/device.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/driver.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/simulation.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/utils.py
This PR adds documentation for the `mil_usb_to_can` package. Closes #515.
> Document the `mil_usb_to_can` package

- docs/reference.rst
Closes #591. Each subheader is replaced with the name of the class under the subheader.
> Remove all Classes subheaders, replace headers with specific class names

- docs/extensions/attributetable.py
- docs/reference.rst
This PR fixes multiple issues with the C++ attribute tables in the Alabaster docs refresh:
- #611 
- #612 
- #613 
- #614
Documentation that previously broke because of these features was updated to support these features.
> Various C++ attribute table fixes in Alabaster

- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/__init__.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/handle.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/packets.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/simulation.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/thruster.py
- docs/subjugator/reference.rst
This PR migrates the `sub8_thrust_and_kill_board` to Python 3, adding support for ROS Noetic. Furthermore, documentation has been added in Alabaster for classes/methods found in this package.
> Migrate the `sub8_thrust_and_kill_board` and add documentation to Alabaster

- docs/_static/custom.css
This adds a color scheme for the admonition for light/dark mode and adds an icon for the admonition.
- #637
> Add icon and colors to See Also admonition in Alabaster docs

- docker/base/system_install
This PR symlinks the `python2` executable to `/usr/bin/python` in the `system_install` script. If already installed, then the symlink process is skipped.
> Symlink `python2` executable to `python`

- docs/_static/custom.js
- docs/_static/sidebar.js
This PR adds several improvements to the Alabaster table of contents:
* #657: When a page is refreshed, the desired section (found in the URL) is automatically scrolled to.
* #610: The scrolling algorithm was improved to move more smoothly.
* #610: The bug caused by sections sharing the same title and breaking the sidebar scrolling was fixed.
* General JavaScript code improvements.
> Improve Alabaster TOC

- docs/design/design.rst
- docs/design/pneumatic_board.md
- docs/reference.rst
- mil_common/drivers/mil_pneumatic_actuator/mil_pneumatic_actuator/__init__.py
- mil_common/drivers/mil_pneumatic_actuator/mil_pneumatic_actuator/board.py
- mil_common/drivers/mil_pneumatic_actuator/mil_pneumatic_actuator/constants.py
- mil_common/drivers/mil_pneumatic_actuator/mil_pneumatic_actuator/simulated_board.py
- mil_common/drivers/mil_pneumatic_actuator/nodes/pneumatic_actuator_node
This PR migrates the `mil_pneumatic_actuator` package to Python 3, and adds documentation on the package throughout the code and to the RST doc.
> Migrate the `mil_pneumatic_actuator` package to Python 3, add documentation

- conf.py
This PR fixes the breaking change introduced by sphinx-doc/sphinx#10474. Currently, the CI is failing because of this breaking change - this should mitigate that problem.
> Update Sphinx language to English, fixes breaking Sphinx change

- NaviGator/utils/remote_control/navigator_joystick_control/nodes/navigator_joystick.py
- #700
- #704 
Because this package only includes nodes, no extensive documentation was added.
> Migrate the `navigator_joystick_control` package to Python 3 for ROS Noetic support

- NaviGator/utils/remote_control/navigator_emergency_control/nodes/navigator_emergency.py
- #699
Typings were added throughout the only node in the package, but documentation may want to be expanded upon later. There is a `README.md` file in the package, and it may be desired to have this file merged into Alabaster.
> Migrate the `navigator_emergency_control` package to Python 3

- NaviGator/mission_control/navigator_launch/launch/perception/passive_sonar.launch
- SubjuGator/command/sub8_launch/launch/subsystems/nav_box.launch
- SubjuGator/command/sub8_launch/launch/subsystems/passive_sonar.launch
This PR fixes some launch scripts by updating the names of various nodes. Many nodes received a `.py` or `.sh` extension which broke some launch files - this PR should fix many of these cases for now.
> Fixed node names in various launch scripts

- docs/navigator/reference.rst
- docs/reference.rst
- docs/subjugator/reference.rst
This PR updates the signatures of all message and service classes in the Alabaster documentation. This PR removes the redundant full import statement. For example:
```diff
--- .. attributetable:: navigator_msgs.srv._MessageDetectDeliver.MessageDetectDeliverRequest
+++ .. attributetable:: navigator_msgs.srv.MessageDetectDeliverRequest
```
> Update the full import signatures for message classes to shortened signatures in Alabaster

- SubjuGator/gnc/sub8_thruster_mapper/nodes/mapper.py
- SubjuGator/gnc/sub8_thruster_mapper/test/test_sub8_mapper.py
- #721
This PR does not add any documentation beside basic typings. Documentation can be added a later date, when more of the functionality in this package is understood in the grand scheme of how our submarine works.
> Migrate `sub8_thruster_mapper` nodes to Python 3

- docs/reference.rst
This PR adds typings and documentation to several classes and methods. Not all methods/classes were documented because the types of some were not clear, and some could not be well understood.
> Add documentation and typings to `txros`

- NaviGator/mission_systems/navigator_scan_the_code/navigator_scan_the_code/__init__.py
This PR operates on the following issue:
- #733
The issue is not closed because the package has not been moved to the deprecated folder. That will occur sometime in the fall semester, likely.
> Issue DeprecationWarning for imports from `navigator_scan_the_code` package

- .github/workflows/issue_non_member.yaml
This PR fixes an issue with one of the GitHub Actions workflows dedicated to handling issues created by users who are not members of MIL.
There was a typo where the `payload` object was referenced, and that has now been fixed.
> Fix broken GitHub Workflow using wrong payload object type

- .github/workflows/gh_pages.yaml
lol oops
Forgot to include the PR number with the concurrency group for GH Pages deployment builds.
> Ensure GitHub Pages concurrency group depends on PR number

- .github/workflows/ci.yaml
This PR adds a step in the CI, where if a user pushed a commit to `master`, the CI will deploy the docs build from that commit to GitHub Pages. Before this, the main `uf-mil.github.io/docs` site was not being updated automatically.
> CI pushes main docs site contents on pushes to master

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
This PR removes the `alex` linter from the list of `pre-commit` hooks used in our repo. Because this linter is based on `node`, installing it can be quite the hassle...
I don't think that it's worth the time investment needed.
> Remove the alex node-based linter from pre-commit

- SubjuGator/command/sub8_missions/sub8_missions/__init__.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/simulation.py
This PR adds two items:
* Adds the missing `SubjuGator` class into the list of exported classes from the `sub8_missions` module
* Removes the debug print statement in the sub8 drivers folder
> Remove unused debug print statement, add missing sub singleton class

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
This PR adds configuration for the `pre-commit` CI bot that helps to update linter versions automatically. This makes it easier to keep our linter specs up to date.
> Add ci config to pre-commit config

- NaviGator/mission_control/navigator_launch/launch/master.launch
- NaviGator/mission_control/navigator_launch/launch/robotx_comms.launch
- NaviGator/mission_control/navigator_missions/navigator_missions/entrance_gate.py
- NaviGator/utils/navigator_msgs/CMakeLists.txt
- NaviGator/utils/navigator_msgs/srv/MessageDetectDeliver.srv
- NaviGator/utils/navigator_msgs/srv/MessageDetectDock.srv
- NaviGator/utils/navigator_msgs/srv/MessageEntranceExitGate.srv
- NaviGator/utils/navigator_msgs/srv/MessageExtranceExitGate.srv
- NaviGator/utils/navigator_msgs/srv/MessageFindFling.srv
- NaviGator/utils/navigator_msgs/srv/MessageFollowPath.srv
- NaviGator/utils/navigator_msgs/srv/MessageIdentifySymbolsDock.srv
- NaviGator/utils/navigator_msgs/srv/MessageReactReport.srv
- NaviGator/utils/navigator_msgs/srv/MessageUAVReplenishment.srv
- NaviGator/utils/navigator_msgs/srv/MessageUAVSearchReport.srv
- NaviGator/utils/navigator_robotx_comms/CMakeLists.txt
- NaviGator/utils/navigator_robotx_comms/navigator_robotx_comms/__init__.py
- NaviGator/utils/navigator_robotx_comms/navigator_robotx_comms/navigator_robotx_comms.py
- NaviGator/utils/navigator_robotx_comms/nodes/robotx_comms_client.py
- NaviGator/utils/navigator_robotx_comms/test/robotx_comms_server.py
- NaviGator/utils/navigator_robotx_comms/test/server.py
- README.md
- docs/index.rst
- docs/navigator/reference.rst
More corrections are needed to simulation environment before we can fully see data from simulation within heartbeat message. However, for now, I corrected the heartbeat client code, along with the code for receiving and sending to td station the entrance/exit gate messages, follow the path messages, wildlife encounter messages, scan the code messages, detect and dock messages, find and fling messages, uav replenishment messages, and the uav search and report messages.
I wrote unittests for each one of these. You can run it with ```rostest navigator_robotx_comms robotx_comms.test```.
The heartbeat message can now be seen from within the simulation environment. The idea is that the simulation environment will be run in the future with ```roslaunch navigator_launch master.launch``` (which …
> Correct heartbeat message client and server to meet 2022 requirements

- NaviGator/mission_control/navigator_launch/launch/gnc/tf.launch
- NaviGator/mission_control/navigator_launch/launch/hardware.launch
- NaviGator/mission_control/navigator_launch/launch/hardware/gps.launch
- NaviGator/simulation/navigator_gazebo/launch/goose.launch
- NaviGator/simulation/navigator_gazebo/urdf/navigator.urdf.xacro
- NaviGator/simulation/navigator_gazebo/urdf/sylphase.xacro
- NaviGator/simulation/navigator_gazebo/urdf/thruster.xacro
- mil_common/drivers/mil_pneumatic_actuator/mil_pneumatic_actuator/simulated_board.py
Corrected urdf issue with NaviGator. You can now run ```roslaunch navigator_launch simulation.launch```, and you will see that no fatal errors occur. Moreover, if you run ```amonitor kill``` to unkill, you can publish a wrench to the wrench_cmd topic to see the boat move. More work needs to be done to make the simulation more complete. Coming soon.
> Corrected urdf issue with NaviGator

- docs/reference/vision.rst
- mil_common/utils/mil_tools/include/mil_tools/image_publisher.hpp
- mil_common/utils/mil_tools/include/mil_tools/image_subscriber.hpp
- mil_common/utils/mil_tools/src/mil_tools/image_publisher.cpp
Before each ImageSubscriber and ImagePublisher instances would have their own NodeHandle instance which is not how it's supposed to be done.
> ImageSubscriber and ImagePublisher now properly use NodeHandle

- mil_common/utils/mil_tools/mil_misc_tools/serial_tools.py
This branch was meant to fix issue  https://github.com/uf-mil/mil/issues/761 '`mil_tools.SimulatedSerial `needs custom `__repr__` and `__str__` methods'
> Added __str__ and __repr__ methods to SimulatedSerial

- NaviGator/navigator.rviz
- docs/reference/poi.rst
- mil_common/utils/mil_poi/mil_poi/__init__.py
- mil_common/utils/mil_poi/mil_poi/server.py
- mil_common/utils/mil_poi/mil_poi/tx_interface.py
This PR adds the following items:
* Restrict POI points to x and y axes (no floating or submerged POIs)
* Document topics and services related to POIs
* Document POI configuration file format
* Refresh POI client class for new documentation format
* Add POI server visualization to default NaviGator rviz config
* None
1. `roslaunch navigator_launch simulation.launch --screen`
2. `nviz`
3. Observe that you are able to move POI points around.
4. Optionally, update the configuration file and re-launch the simulation to observe new default POIs.
> Update POI server

- docs/reference/txros/api.rst
- docs/reference/txros/errors.rst
This PR adds the following to `txros`:
* `pre-commit` for easier developer interaction
* Support for multiple subscriptions/publications to the same topic on the same node handle
* Better explanation of handling high-rate publishers
* Testing high-rate subscribers/publishers
* Testing multiple subscriptions to the same topic using the same `txros.NodeHandle`
* Support for ensuring all messages from a short-lived publisher are read using `txros.Subscriber.recently_read`
* String representation of `txros.ServiceClient`, `txros.Service`, `txros.Publisher`, `txros.Subscriber`
* `txros.AlreadySetup` exception to indicate resource has already been `setup()`
* Raising `TypeError` for incorrect types provided to parameter methods for `txros.NodeHandle`
Not relevant
* None
Run `rostest txros …
> Add more reliability/testing to `txros` publishers and subscribers

- NaviGator/gnc/navigator_thrust_mapper/navigator_thrust_mapper/thruster_map.py
- NaviGator/simulation/navigator_gazebo/urdf/navigator.urdf.xacro
NaviGator now has the ability to provide different mechanical reductions to each thruster. This means, if one thruster (for some reason is outputting less force than another given the same input current, we can modify the ratio that is multiplied by the input provided by the thruster mapper.
Go to ```navigator_gazebo/urdf/navigator.urdf.xacro```. Change any of the mechanical reduction parameters in the file. If you try to provide a wrench on the real boat, you will see that one thruster moves slower than another when you provide a forward wrench (which will provide the same input current to each of the thrusters).
> Added ability to give thrusters separate mechanical reductions

- scripts/setup.bash
This PR adds Python 3 typing to `txros`, making it easier for developers to quickly use the library.
None, library changes.
None
Verify that all CI tests pass. You can optionally run `pyright` in the `txros` library folder and observe that no type issues arise (in non-strict mode).
> Add Python 3 typing to `txros`

- NaviGator/mission_control/navigator_missions/navigator_missions/go_to_poi.py
- NaviGator/mission_control/navigator_missions/navigator_missions/pose_editor.py
- mil_common/utils/mil_poi/mil_poi/server.py
- mil_common/utils/mil_poi/mil_poi/tx_interface.py
- mil_common/utils/mil_poi/msg/POI.msg
POI objects now have orientation, and the `GoToPOI` mission has been adjusted to implement this.
None
* None
1. `roslaunch navigator_launch simulation.launch --screen`
1. Open `nviz`
1. Drag the `start_gate` POI to a new position/orientation
1. `mission run GoToPOI start_gate`
1. Observe that NaviGator goes to the POI with the orientation and position required.
<!-- BELOW: Have you checked the following? -→
> Add orientation values to POIs

- scripts/setup.bash
Not relevant
* #XXX
Observe that no issues are found when using the shell environment
> Fix accidental literal comparison between command and literal

- .github/workflows/gh_pages.yaml
- .pre-commit-config.yaml
[Recently, `ubuntu-latest` container was updated to use Ubuntu 20 instead of Ubuntu 22.](https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) As a result, `rsync` has had issues being installed in the GitHub Actions deployment runner.
None, Github Actions only.
* None
None
> Use `ubuntu-20.04` for GitHub Pages generation container

- .github/workflows/ci.yaml
The container used to deploy docs from `master` is broken by the upgrade to Ubuntu 22.04. Should have been included in #960, but forgot. 😛 
None, container stuff.
* #XXX
None
> Fix container type for container deploying docs from master

- SubjuGator/command/subjugator_launch/config/course_geometry.yaml
- SubjuGator/command/subjugator_launch/launch/sub8.launch
- SubjuGator/command/subjugator_missions/subjugator_missions/start_gate_2022.py
This PR adds the ability for the sub to rotate to a specific orientation before moving through the start gate. This is used for the "Coin Flip" task, where the sub could start in any orientation before being required to move through the start gate.
https://user-images.githubusercontent.com/52760912/223162810-55a03d85-3d75-4c26-a66a-e732acc03d67.mp4
* #992
Run the `StartGate2022` mission and observe that the sub orients to a specific direction first.
> Sub now rotates to specific orientation before moving through start gate

- docs/reference/alarms.rst
- scripts/build_docs
This PR adds a small amount of code to cause the `build_docs` script to fail whenever the Sphinx doc compilation fails.
None, basic change.
* #832
See CI output
> Errors in Sphinx compilation will cause build_docs script to fail

- .github/workflows/gh_pages.yaml
The package index from the runner image will go out of date and dependencies may be unresolveable. If upgrade is run before update the index can be stale for the upgrade step.
Updated order of commands in install rsync step of gh pages ci.
Closes #1000 
If CI build completes, the issue is resolved. The issue is intermittent, and depends on the state of the runner container's last update time.
> Run apt-get update before upgrade

- .github/PULL_REQUEST_TEMPLATE.md
Resolves #1004 by changing the PR template to use a '-' instead of a bullet point under the "Related Issues" section, and promoting the use of Github's keywords by explicitly saying "Closes \#XXX" to link the PR to the corresponding issue.
* Closes #1004 
After merging to master, ensure that the new template is used when submitting a new PR, and properly links to the correct issue.
> Amends PR template to link to issue

- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/handle.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/packets.py
- SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/thruster.py
remove hardcoded thruster name id map from script to it's only in `Subjugator/gnc/subjugator_thruster_mapper/config/thruster_layout.yaml` file and not in the yaml and in hardcoded in `SubjuGator/drivers/sub8_thrust_and_kill_board/sub8_thrust_and_kill_board/packets.py`.
- Run the sub normally in hardware
- Change node_id in the yaml file and see the how the effort changes to a different thruster
This simplifies where the ids so no documentation is needed. Ids are only now in the yaml where users should expect them.
> remove hardcoded thruster name id map from script to it's only in yaml

- .github/ISSUE_TEMPLATE/navigator.yaml
I removed the assignee and deadline fields in the navigator.yaml file in .github/ISSUE_TEMPLATE.
\- Closes #1091 
They can just create a new issue to see that the assignee and deadline fields no longer exist.
> Removed the assignee and deadline fields from the github issue template

- SubjuGator/simulation/subjugator_gazebo/urdf/sub8.urdf.xacro
- mil_common/gnc/odometry_utils/src/odometry_to_tf.cpp
(finally!) fixes #889!
This checks to see if a transform has already been published for a transform with a similar timestamp, and if so, ignores it rather than publishing it. This helps to get rid of the `TF_REPEATED_DATA` that spams the console.
> Limit TF_REPEATED_DATA messages by checking for repeated transforms

- .github/workflows/ci.yaml
- scripts/install.sh
This fixes the `pip3 not found` issue in CI. I think this happened as a result of updating the docker image
Look at the CI logs
None
None
> Fix pip3 in CI

- mil_common/gnc/odometry_utils/src/odometry_to_tf.cpp
#1097 broke the `odometry_to_tf` node because it filters out _all_ odom messages after the first one is sent. oopses!
This PR fixes that by just making sure that no messages are sent that have exactly the same timestamp.
\- Closes #XXX
> Fix odom messages being converted to tf

- scripts/install.sh
- scripts/setup.bash
Does pretty much what it sounds like!
\- Closes #XXX
> Add aptitude as installed package, cmonly for building just one package with catkin_make

- SubjuGator/drivers/sub9_thrust_and_kill_board/sub9_thrust_and_kill_board/packets.py
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/sub9/packet.py
Changes the sub9 usb to can board driver and drivers that run on it to remove padding from the structs that are created. Currently, native padding is used which causes "Bf" for example to be 8 bytes instead of 5. This solves this by adding "=" to the beginning of the payload strings to enforce no padding.
> Remove padding from python struct packing

- docs/reference/axros/examples.rst
Remove last mentions of txROS from API documentation, fix spelling mistakes in axros documentation
\- Closes #XXX
> txROS Updates

- SubjuGator/drivers/sub9_thrust_and_kill_board/sub9_thrust_and_kill_board/__init__.py
- SubjuGator/drivers/sub9_thrust_and_kill_board/sub9_thrust_and_kill_board/packets.py
- SubjuGator/drivers/sub9_thrust_and_kill_board/test/simulated_board_test.py
- SubjuGator/drivers/sub_actuator_board/sub_actuator_board/packets.py
- SubjuGator/drivers/sub_actuator_board/test/simulated_board_test.py
- docs/subjugator/reference.rst
- mil_common/drivers/mil_usb_to_can/mil_usb_to_can/sub9/packet.py
- mil_common/drivers/mil_usb_to_can/test/test_packets_sub9.py
Changes:
* Tests for Fletcher's checksum
* Tests for `sub_actuator_board` and `sub9_thrust_and_kill_board` packages (closes #1166)
* Fixing incorrectly set SYNC CHAR
* Adding enums for thruster ID
* Enforcing little endianness for all packets
\- Closes #XXX
> More reliability for `mil_usb_to_can`

- NaviGator/utils/navigator_battery_monitor/nodes/navigator_battery_monitor.py
Manually migrated navigator_battery_monitor package from ros1 to ros2.
> navigator_battery_monitor package migrated to ros2

- SubjuGator/command/subjugator_launch/launch/subsystems/nav_box.launch
- SubjuGator/command/subjugator_launch/package.xml
- SubjuGator/drivers/nav_tube_driver/CMakeLists.txt
- SubjuGator/drivers/nav_tube_driver/package.xml
- SubjuGator/drivers/nav_tube_driver/src/nav_tube_driver.cpp
Adds in the code required to access depth data from the new nav tube.
\- Closes #1123 #1121 and #1120
Tested code in lab to verify driver works and verified launch file works.
> Nav tube update

- README.md
- SubjuGator/simulation/subjugator_simulation/subjugator_sim_tools/physics/vehicle.py
- SubjuGator/utils/subjugator_msgs/CMakeLists.txt
- SubjuGator/utils/subjugator_msgs/msg/VelocityMeasurement.msg
- SubjuGator/utils/subjugator_msgs/msg/VelocityMeasurements.msg
- mil_common/gnc/odom_estimator/src/nodelet.cpp
- mil_common/utils/mil_msgs/msg/VelocityMeasurement.msg
- mil_common/utils/mil_msgs/msg/VelocityMeasurements.msg
- scripts/install.sh
[See commit messages]
N/A
* #1175
N/A
> Merge miscellaneous tweaks (mostly doc improvements) made while assisting with DVL debugging 

- mil_common/ros_alarms_msgs/CMakeLists.txt
- mil_common/ros_alarms_msgs/msg/Alarms.msg
- mil_common/ros_alarms_msgs/package.xml
- mil_common/ros_alarms_msgs/srv/AlarmGet.srv
Migrated `ros_msgs_alarms` to ROS2.
move the package to a working ros2 workspace and run:
1. `colcon build --packages-select ros_alarms_msgs`
2. `source install/setup.bash`
3. `ros2 interface show ros_alarms_msgs/msg/Alarm`
4. `ros2 interface show ros_alarms_msgs/msg/Alarms`
> Migrate ros_alarms_msgs

- .github/workflows/ci.yaml
- SubjuGator/simulation/subjugator_gazebo/CMakeLists.txt
- SubjuGator/simulation/subjugator_gazebo/package.xml
- SubjuGator/simulation/subjugator_gazebo/test/spawn_test.cpp
- SubjuGator/simulation/subjugator_gazebo/test/subjugator_gazebo.test
- mil_common/utils/mil_tools/include/mil_tools/test.hpp
- mil_common/utils/mil_tools/src/mil_tools/mil_tools.cpp
- scripts/setup.bash
> add test: SubjuGator can spawn in Gazebo

- SubjuGator/drivers/nav_tube_driver/src/nav_tube_driver.cpp
- SubjuGator/gnc/subjugator_thruster_mapper/config/thruster_layout.yaml
> Dynamic pressure, move thrusters from Fall 2023

- mil_common/mil_missions/nodes/mission_server
> mil_missions: Wait until all missions come alive before attempting to run a requested mission

- .github/workflows/autopush.yaml
- scripts/setup.bash
> Add autopush workflow

- mil_common/drivers/mil_passive_sonar/CMakeLists.txt
- mil_common/drivers/mil_passive_sonar/scripts/ping_publisher.py
- mil_common/drivers/mil_passive_sonar/src/fakeping_pipeline.sh
- mil_common/drivers/mil_passive_sonar/src/pipeline.sh
This PR creates a bash script pipeline for posting the sdgps ping solution message over TCP (fakeping_pipeline.sh creates a fake ping for testing, and pipeline.sh receives real hydrophone pings).  Then, when running the python node ping_publisher.py, it will accept those TCP messages and publish them to the ROS node /ping for future use. These changes are part of the ROS package mil_passive_sonar.
Each panel started in order: 
Bottom: Debug messages after running "rosrun mil_passive_sonar fakeping_pipeline.sh"
Upper left: Debug messages after running "rosrun mil_passive_sonar ping_publisher.py"
Upper right: Desired result of running "rostopic echo /ping"
\- Closes #1288
As shown in the image above, open three terminal windows (in tmux for ease of access). In one, run "rosrun …
> python publisher for sdgps solution to hydrophone pings

- NaviGator/scripts/tmux_start.sh
- scripts/setup.bash
Sets up a bash alias called 'ntmux' short for Navigator tmux, that opens tmux session called 'auto' with two windows. It launches navigator and sets up kill monitors, as well as blank panes for additional commands.
Run 'ntmux' and check the appropriate session is started or is opened.
> bash alias 'ntmux'
